# version: '3.9'

# services:
#   app:
#     build: .
#     command: yarn dev
#     ports:
#       - '3000:3000'
#     volumes:
#       - .:/usr/app
    
#   db:
#     container_name: 'localhost'
#     image: postgres
#     ports:
#       - 5432:5432
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=123456
#       - POSTGRES_DB=postgres